version: "3"

services:
  sails:
    build: .
    ports:
      - "1337:1337"
    volumes:
      - ./:/sails
    command: npm start
    environment:
      - NODE_ENV=dev
    depends_on:
      - "mongo"
  
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
